//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "usr", table_name = "user_profiles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub usr_id: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub biography: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub avator: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub background: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub contact_me: Option<Json>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::usr_info::Entity",
        from = "Column::UsrId",
        to = "super::usr_info::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UsrInfo,
}

impl Related<super::usr_info::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsrInfo.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
