[server]
port = 10086
ipv4_enabled = false
ipv6_enabled = true
secret_key = "SGVsbG8gd29ybGQ="

[server.log]
with_ansi = true
with_file = false
with_thread = true
with_target = true
log_level = "trace"
dump_path = "log"

[database]
host = "localhost"
port = 5432
user = "postgres"
password = "123456"
database = "br_ovfl"
max_connection = 80
min_connection = 4
