[server]
port = 10086
ipv6_enabled = true
# secret_key = "SGVsbG8gd29ybGQ="

[logger]
with_ansi = true
with_file = true
with_thread = true
with_target = true
level = "trace"

[database]
host = "localhost"
port = 5432
user = "postgres"
password = "123456"
database = "br_ovfl"
max_connection = 80
min_connection = 4
