# 鉴权模块的配置，这里配置如何签发令牌
[auth.encoder]
encoding_keys = [
    { algorithm = "HS256", form = "der_inline", kid = "key 1", key = "dGVzdDE="}
]
issue_as = "brain overflow"
audience = ["brain overflow"]
expires_in = 3600
not_valid_in = 0

# 鉴权模块的配置，这里配置如何解码令牌
[auth.decoder]
decoding_keys = [
    ["brain overflow", { algorithm = "HS256", form = "der_inline", kid = "key 1", key = "dGVzdDE=" }]
]
leeway = 60
reject_tokens_expiring_in_less_than = 0
audience = [ "brain overflow" ]

# 数据库配置
[database]
host = "postgres"
port = 5432
username = "postgres"
password = "123456"
database = "brain-overflow"

[redis]
url = "redis://redis"

[logger]
level = "info"
with_file = false
with_target = false
with_thread = false

[s3]
bucket = "brain-overflow"           # 哪一个桶
access_key_id = "minioadmin"        # 用户名和密码
secret_access_key = "minioadmin"
force_path_style = true             # 默认就是路径的形式而非子域名的形式，此处只是为了更加明确
endpoint = "http://localhost:9000"  # 容器暴露出来的端点，也可以是 aws 的端点
url_ttl = 3600                      # 预签名 url 的过期时间

# 端口配置
[server]
port = 10086
ipv6 = false
