version: '3.8'

networks:
  brain-overflow-network:
    driver: bridge

volumes:
  postgres_data:
  minio_data:

services:
  postgres:
    image: docker.io/library/postgres:18
    container_name: brain-overflow-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: brain-overflow
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./sql/ddl/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - brain-overflow-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 120

  minio:
    image: quay.io/minio/minio:latest
    container_name: brain-overflow-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      # webhook 回调
      MINIO_NOTIFY_WEBHOOK_ENABLE_primary: on
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_primary: http://brain-overflow:10086/s3/webhook
      # 开启跨域
      MINIO_CORS_ENABLE: on
      MINIO_CORS_ALLOW_ORIGINS: "*"
      MINIO_CORS_ALLOW_METHODS: "GET,PUT,POST,DELETE,HEAD"
      MINIO_CORS_ALLOW_HEADERS: "*"
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - brain-overflow-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 1s
      timeout: 5s
      retries: 120

  minio-setup:
    image: quay.io/minio/mc
    container_name: brain-overflow-minio-setup
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - brain-overflow-network
    entrypoint: >
      /bin/sh -c "
      until mc alias set brain-overflow http://minio:9000 minioadmin minioadmin; do
          echo 'Waiting for MinIO to be ready...';
          sleep 1;
      done &&
      echo 'Creating bucket brain-overflow if not exists...' &&
          mc mb brain-overflow/brain-overflow --ignore-existing &&
      echo 'Bucket brain-overflow created or already exists' &&

      echo 'Creating webhook of brain-overflow' &&
          # 如果用命令行，minio 会检验这个端点的可达性，显然不行，所以我们使用环境变量
          # mc admin config set brain-overflow notify_webhook:primary \
          #     endpoint='http://brain-overflow:10086/s3/webhook' &&
          # mc admin service restart brain-overflow &&
          mc event add brain-overflow/brain-overflow \
              arn:minio:sqs::primary:webhook --event put,delete &&
          mc event ls brain-overflow/brain-overflow \
              arn:minio:sqs::primary:webhook &&
      echo 'Webhook set to http://brain-overflow:10086/s3/webhook, listening put and delete'"
    restart: "no"

  redis:
    image: docker.io/library/redis:8.6.2
    container_name: brain-overflow-redis
    networks:
      - brain-overflow-network
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 5s
      retries: 120

  brain-overflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brain-overflow-app
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      minio-setup:
        condition: service_completed_successfully
    volumes:
      - ./brain-overflow.toml:/app/brain-overflow.toml:ro
    ports:
      - "10086:10086"
    networks:
      - brain-overflow-network
    restart: unless-stopped
